#GLOBAL VARIABLES
#===========================================================
#CONSTANTS
#"Enums" for conversationHandler's Dictionary
ACTION, GETTITLE, GETTEXT, GENERATETEXT, SENDING, POSTTOMANAGE, MANAGEPOST, DELETEPOST, EDITPREVIEW, EDIT, ASKFORPHOTO, EDITPHOTO, EDITPHOTOPOST, CHANGESTATUS, DELETEPOSTCONFIRM, FEEDBACK = range(16)


#Channel ID to forward messages to, bot must be Admin in the channel
CHANNELID = -1001475820789
CHANNELLINKID = 1475820789 #ChannelID without the -100
ADMINCHANNELID = -1001499568418
#Token for the bot
TOKEN = '1563235877:AAHE4XZN8b66xAfmfi74ZxQ2uJkYhwUZmYA'